### ISSUE TITLE
Auto-build, tags, etc.

### ISSUE THREAD

**Issue by gallais** [clarus/cuisine#1]
Hi guillaume,

FYI, with a bunch of friends from Lyon we also have a
repo for recipes and we noticed that after a bit it's easier
to explore it if things are sorted in various categories.
Hence a bunch of build scripts handling a tag system
and a Travis instance taking care of deployment.

If you're interested, you can have a look [here](https://github.com/impega/reciptacle) and see
the result [here](http://impega.github.io/reciptacle/).

**Comment by clarus** [comment]
Hi,

Thanks for the nice script in shell! :) This is cool to see such technologies used for cooking. I will keep that in mind once I get enough recipes.
